In [26]:
with open("/home/qzj517/POR-DD/gflownet/mols/data/blocks_PDB_105.json") as f:
    data = f.read()

In [27]:
d = eval(data)

In [40]:
block_smi = list(d["block_smi"].values())
block_rs = list(d["block_r"].values())
block_names = list(d["block_name"].values())

In [42]:
import numpy as np

In [45]:
true_block_set = sorted(set(block_smi))

In [50]:
import pandas as pd

In [53]:
df_smi = pd.DataFrame(block_smi)
df_r = pd.DataFrame(block_rs)

In [59]:
df_r

0    1    2    3    4    5
0    0  1.0  2.0  3.0  4.0  5.0
1    0  1.0  NaN  NaN  NaN  NaN
2    1  0.0  0.0  0.0  NaN  NaN
3    0  NaN  NaN  NaN  NaN  NaN
4    0  3.0  NaN  NaN  NaN  NaN
..  ..  ...  ...  ...  ...  ...
100  8  4.0  7.0  NaN  NaN  NaN
101  7  4.0  8.0  NaN  NaN  NaN
102  4  7.0  8.0  NaN  NaN  NaN
103  1  NaN  NaN  NaN  NaN  NaN
104  5  NaN  NaN  NaN  NaN  NaN

[105 rows x 6 columns]

In [68]:
a_smi = np.array(block_smi)
a_rs = np.array(block_rs)

/home/qzj517/anaconda3/envs/equibind/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [83]:
a_rs[a_smi == "CO"]

array([list([0, 1]), list([1, 0, 0, 0])], dtype=object)

In [88]:
maxed = []
for unique_smi in true_block_set:
    mask = a_smi == unique_smi
    r_for_all_relevant_smi = a_rs[mask]
    maxed.append(max([max(x)+1 for x in r_for_all_relevant_smi]))


In [97]:
maxed = np.array(maxed)

In [94]:
mask2 = ~(np.array([max(block_rs[block_smi.index(i)])+1 for i in true_block_set]) == np.array(maxed))

In [104]:
[true_block_set.index(i) for i in block_smi]

[65,
 31,
 31,
 19,
 9,
 9,
 9,
 43,
 1,
 66,
 66,
 66,
 30,
 30,
 20,
 44,
 45,
 25,
 64,
 64,
 41,
 41,
 6,
 27,
 27,
 36,
 39,
 28,
 47,
 35,
 10,
 10,
 71,
 71,
 62,
 62,
 63,
 13,
 7,
 40,
 70,
 70,
 49,
 8,
 8,
 8,
 68,
 68,
 68,
 68,
 50,
 37,
 67,
 51,
 60,
 21,
 38,
 55,
 55,
 29,
 69,
 69,
 69,
 0,
 12,
 61,
 61,
 5,
 15,
 11,
 11,
 11,
 22,
 42,
 26,
 23,
 2,
 24,
 57,
 57,
 4,
 4,
 17,
 17,
 32,
 53,
 33,
 16,
 18,
 46,
 59,
 59,
 54,
 3,
 3,
 3,
 56,
 56,
 48,
 52,
 58,
 58,
 58,
 34,
 14]

In [98]:
maxed[mask2]

array([4, 3, 3])

In [100]:
np.array([max(block_rs[block_smi.index(i)])+1 for i in true_block_set])[mask2]

array([1, 1, 1])

In [90]:
maxed

[1,
 1,
 1,
 4,
 3,
 1,
 1,
 6,
 5,
 4,
 5,
 6,
 6,
 6,
 6,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 7,
 9,
 5,
 9,
 7,
 1,
 4,
 3,
 7,
 3,
 6,
 6,
 5,
 5,
 6,
 4,
 7]

In [82]:
[x[0] == max(x) for x in a_rs[a_smi == "CO"]]

[False, True]

In [80]:
[[x[0] == max(x) for x in a_rs[a_smi == unique_smi]] for unique_smi in true_block_set]


[[True],
 [True],
 [True],
 [True, True, True],
 [False, True],
 [True],
 [True],
 [False],
 [False, False, False],
 [False, False, True],
 [False, False],
 [False, False, False],
 [False],
 [True],
 [True],
 [False],
 [True],
 [False, True],
 [True],
 [True],
 [False],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [False, True],
 [True],
 [True],
 [False, True],
 [False, True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [False, True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [True],
 [False, True],
 [False, True],
 [False, True],
 [True, False, False],
 [False, True],
 [True],
 [False, True],
 [True, True],
 [True],
 [True, True],
 [False],
 [False, False, False],
 [False],
 [False, False, True, False],
 [False, False, False],
 [False, True],
 [False, True]]

In [78]:
[all([max(x) for x in a_rs[a_smi == unique_smi]]) for unique_smi in true_block_set]

[False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [62]:
df_smi == 'C1=CCCCC1'

0
0    False
1    False
2    False
3    False
4    False
..     ...
100  False
101  False
102  False
103  False
104  False

[105 rows x 1 columns]

In [61]:
df_r.loc[]

ValueError: Cannot index with multidimensional key

In [46]:
np.int32([0] + list(np.cumsum([max(block_rs[block_smi.index(i)])+1 for i in true_block_set])))

array([  0,   1,   2,   3,   4,   7,   8,   9,  15,  20,  24,  29,  35,
        41,  47,  53,  55,  56,  58,  59,  60,  62,  64,  66,  69,  71,
        73,  75,  77,  79,  80,  83,  85,  86,  87,  89,  90,  91,  93,
        94,  95,  97,  99, 101, 102, 104, 106, 108, 110, 112, 114, 116,
       118, 120, 122, 124, 131, 140, 145, 154, 161, 162, 166, 167, 174,
       175, 181, 187, 192, 197, 203, 207, 214], dtype=int32)

In [47]:
true_block_set

['Br',
 'C',
 'C#N',
 'C1=CCCCC1',
 'C1=CNC=CC1',
 'C1CC1',
 'C1CCCC1',
 'C1CCCCC1',
 'C1CCNC1',
 'C1CCNCC1',
 'C1CCOC1',
 'C1CCOCC1',
 'C1CNCCN1',
 'C1COCCN1',
 'C1COCC[NH2+]1',
 'C=C',
 'C=C(C)C',
 'C=CC',
 'C=N',
 'C=O',
 'CC',
 'CC(C)C',
 'CC(C)O',
 'CC(N)=O',
 'CC=O',
 'CCC',
 'CCO',
 'CN',
 'CNC',
 'CNC(C)=O',
 'CNC=O',
 'CO',
 'CS',
 'C[NH3+]',
 'C[SH2+]',
 'Cl',
 'F',
 'FC(F)F',
 'I',
 'N',
 'N=CN',
 'NC=O',
 'N[SH](=O)=O',
 'O',
 'O=CNO',
 'O=CO',
 'O=C[O-]',
 'O=PO',
 'O=P[O-]',
 'O=S=O',
 'O=[NH+][O-]',
 'O=[PH](O)O',
 'O=[PH]([O-])O',
 'O=[SH](=O)O',
 'O=[SH](=O)[O-]',
 'O=c1[nH]cnc2[nH]cnc12',
 'O=c1[nH]cnc2c1NCCN2',
 'O=c1cc[nH]c(=O)[nH]1',
 'O=c1nc2[nH]c3ccccc3nc-2c(=O)[nH]1',
 'O=c1nccc[nH]1',
 'S',
 'c1cc[nH+]cc1',
 'c1cc[nH]c1',
 'c1ccc2[nH]ccc2c1',
 'c1ccc2ccccc2c1',
 'c1ccccc1',
 'c1ccncc1',
 'c1ccsc1',
 'c1cn[nH]c1',
 'c1cncnc1',
 'c1cscn1',
 'c1ncc2nc[nH]c2n1']

In [7]:
data = [[j for j in i.values()] for i in d.values()]

In [14]:
data = list(zip(*data))

In [25]:
data[5]

('C1CCNCC1_1', 'C1CCNCC1', [1, 0, 3])